unit testcase for checkpoint validation during create data stream
suranjan/yugabyte-db pull request #39
Opened 2022-02-11 07:09 UTC by sureshdash2022-yb

please review those testcases
@suranjan @vaibhav-yb @isha-yb

2022-02-11 09:22 UTC, vaibhav-yb requested changes

2022-02-11 09:22 UTC, vaibhav-yb commented on ent/src/yb/integration-tests/cdcsdk_stream-test.cc
> +    uint32_t options_sz = list_streams.Get(i).options_size();
`const uint32_t options_sz`

2022-02-11 09:22 UTC, vaibhav-yb commented on ent/src/yb/integration-tests/cdcsdk_stream-test.cc
> +      string curKey = list_streams.Get(i).options(j).key();
In cpp, the we follow snake casing so the variable would be `cur_key` and `cur_value` in the next line.

2022-02-11 09:22 UTC, vaibhav-yb commented on ent/src/yb/integration-tests/cdcsdk_stream-test.cc
> +
Same changes are required here
* snake casing in variable names
* Writing comments correctly

2022-02-11 10:38 UTC, sureshdash2022-yb commented on ent/src/yb/integration-tests/cdcsdk_stream-test.cc
> +
Fixed

2022-02-11 10:38 UTC, sureshdash2022-yb commented on ent/src/yb/integration-tests/cdcsdk_stream-test.cc
> +      string curKey = list_streams.Get(i).options(j).key();
Fixed

2022-02-11 10:38 UTC, sureshdash2022-yb commented on ent/src/yb/integration-tests/cdcsdk_stream-test.cc
> +    uint32_t options_sz = list_streams.Get(i).options_size();
Fixed

2022-02-11 10:38 UTC, sureshdash2022-yb commented on ent/src/yb/integration-tests/cdcsdk_stream-test.cc
> +  //get the list of dbstream
Fixed

2022-02-11 10:39 UTC, sureshdash2022-yb commented
@vaibhav-yb @suranjan @isha-yb  fixed those review comments

2022-02-15 05:32 UTC, suranjan approved these changes

2022-02-15 05:33 UTC, merged